"""Generate the repository's idempotent learning-resource initialization data."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path


ROOT = Path(__file__).parents[2]
OUTPUT = ROOT / "backend" / "src" / "main" / "resources" / "learning-resources-data.sql"
CONTENT_ROOT = ROOT / "backend" / "learning_content"


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if not spec or not spec.loader:
        raise RuntimeError(f"无法加载模块: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def sql(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def main() -> int:
    catalog = load_module("catalog_seed", ROOT / "scripts" / "data_import" / "seed_chinese_resource_catalog.py")
    crawler = load_module("series_crawler", ROOT / "scripts" / "crawlers" / "crawl_chinese_learning_series.py")
    lines = [
        "-- Generated by scripts/data_import/build_learning_resources_init.py",
        "-- Safe to run repeatedly: existing URLs, series, and documents are preserved.",
        "",
    ]

    for item in catalog.RESOURCES:
        values = (item.title, item.author, item.category, item.resource_type, item.description, item.url,
                  item.duration, item.difficulty, True, 0, item.rating, item.tags, "active")
        lines.append(
            "INSERT INTO learning_resources "
            "(title, author, category, resource_type, description, url, duration, difficulty_level, is_free, price, rating, tags, status) VALUES "
            f"({', '.join(sql(value) for value in values)}) ON CONFLICT (url) DO NOTHING;"
        )

    lines.append("")
    for series in crawler.SERIES:
        values = (series.slug, series.title, series.provider, series.category, series.description,
                  series.repository_url, series.source_site_url, "zh-CN")
        lines.append(
            "INSERT INTO learning_resource_series "
            "(slug, title, provider, category, description, repository_url, source_site_url, language) VALUES "
            f"({', '.join(sql(value) for value in values)}) ON CONFLICT (slug) DO NOTHING;"
        )

    document_count = 0
    lines.append("")
    for series in crawler.SERIES:
        series_root = CONTENT_ROOT / series.slug
        markdown_files = sorted(series_root.rglob("*.md"), key=lambda path: crawler.document_sort_key(path.relative_to(series_root)))
        for order, source_path in enumerate(markdown_files):
            relative_path = source_path.relative_to(series_root)
            content = source_path.read_text(encoding="utf-8")
            title = crawler.markdown_title(content, relative_path)
            source_url = f"{series.repository_url}/blob/{series.branch}/{series.content_subdir}/{relative_path.as_posix()}"
            local_path = f"{series.slug}/{relative_path.as_posix()}"
            values = (title, relative_path.as_posix(), local_path, source_url, order, series.slug)
            lines.append(
                "INSERT INTO learning_resource_documents (series_id, title, relative_path, local_path, source_url, sort_order) "
                f"SELECT id, {sql(values[0])}, {sql(values[1])}, {sql(values[2])}, {sql(values[3])}, {sql(values[4])} "
                f"FROM learning_resource_series WHERE slug = {sql(values[5])} ON CONFLICT (series_id, relative_path) DO NOTHING;"
            )
            document_count += 1

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"已生成 {OUTPUT}：{len(catalog.RESOURCES)} 条分类资源，{len(crawler.SERIES)} 个系列，{document_count} 篇文档")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
